version: '3.4'

services:
  app:
    build:
      context: .
      target: builder
    restart: always
    environment:
      NODE_ENV: production
      NODE_PORT: ${NODE_PORT}
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    env_file:
      - .env
    networks:
      - webnet
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links: 
      - db
    depends_on: 
      - db
  db:
    image: postgres:12
    networks:
      - webnet
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ec_shopping-cart_sql-data:/var/lib/postgresql/data

networks:
  webnet:

volumes:
  ec_shopping-cart_sql-data:
